branches:
  only:
  - master
  - develop
  - "/^releases\\/.*$/"
jobs:
  fast_finish: true
  include:
  - stage: flake8
    python: '2.7'
    os: linux
    language: python
    env: TEST_SUITE=flake8
  - stage: unit tests + documentation
    python: '2.6'
    os: linux
    language: python
    env: TEST_SUITE=unit
  - python: '2.7'
    os: linux
    language: python
    env:
    - TEST_SUITE=unit
    - COVERAGE=true
  - python: '3.3'
    os: linux
    language: python
    env: TEST_SUITE=unit
  - python: '3.4'
    os: linux
    language: python
    env: TEST_SUITE=unit
  - python: '3.5'
    os: linux
    language: python
    env: TEST_SUITE=unit
  - python: '3.6'
    os: linux
    language: python
    env:
    - TEST_SUITE=unit
    - COVERAGE=true
  - os: osx
    language: generic
    env:
    - TEST_SUITE=unit
    - PYTHON_VERSION=2.7
    - COVERAGE=true
  - python: '2.7'
    os: linux
    language: python
    env: TEST_SUITE=doc
  - stage: build tests
    python: '2.7'
    os: linux
    language: python
    env:
    - TEST_SUITE=build
    - COVERAGE=true
    - SPEC=mpich
  - python: '2.7'
    os: linux
    language: python
    env:
    - TEST_SUITE=build
    - COVERAGE=true
    - SPEC=astyle
  - python: '2.7'
    os: linux
    language: python
    env:
    - TEST_SUITE=build
    - COVERAGE=true
    - SPEC=tut
  - python: '2.7'
    os: linux
    language: python
    env:
    - TEST_SUITE=build
    - COVERAGE=true
    - SPEC=py-setuptools
  - python: '2.7'
    os: linux
    language: python
    env:
    - TEST_SUITE=build
    - COVERAGE=true
    - SPEC=openjpeg
  - python: '2.7'
    os: linux
    language: python
    env:
    - TEST_SUITE=build
    - COVERAGE=true
    - SPEC=r-rcpp
  - python: '3.6'
    os: linux
    language: python
    env:
    - TEST_SUITE=build
    - COVERAGE=true
    - SPEC=mpich
sudo: false
addons:
  apt:
    packages:
    - gfortran
    - mercurial
    - graphviz
    - gnupg2
    - cmake
    - r-base
    - r-base-core
    - r-base-dev
    - perl
    - perl-base
cache: pip
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions python > /dev/null
  || brew install python; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions gcc    > /dev/null
  || brew install gcc;    fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions gnupg2 > /dev/null
  || brew install gnupg2; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
install:
- pip install --upgrade pip
- pip install --upgrade six
- pip install --upgrade setuptools
- pip install --upgrade codecov
- pip install --upgrade flake8
- if [[ "$TEST_SUITE" == "doc" ]]; then pip install --upgrade -r lib/spack/docs/requirements.txt;
  fi
before_script:
- git config --global user.email "spack@example.com"
- git config --global user.name "Test User"
- git fetch origin develop:develop
- if [[ "$TEST_SUITE" == "build" ]]; then cp share/spack/qa/configuration/packages.yaml
  etc/spack/packages.yaml; fi
script: share/spack/qa/run-$TEST_SUITE-tests
after_success:
- codecov --env PY_VERSION
notifications:
  slack:
    secure: OaCmFtAl3CcB6WqlJjCvYpg8B2R1i/X2xqe+ERsGR72IiqrkqzcHuYdXdz7agbPrlDmXDRYjmPeY0whIBdHaQmiz+67VCynNoXT1VUnQz3xt6LwtGkJXdzpO/cLG2DVAMjFxpxTCQryf7ve4mCOCQ6mSMPcMXnPgWwy67PhZaonxpCgTDvVivmzAzEf02AxB6kvyrCEeohx4lzkAk2AhlpL+osjTrozcce1SBQjMoVDZppMFuoogZP/Vhtx7GShFSZ3mICrSSC+Y7axaGUS9xaTzdy8XfbsP3xfbmNm25ApJataBy1t7ErR/BVwNfCr88dkb3jaxWosEvXXUi+qLbVdM3RHjmSBNGUScHI2W2p3R7yxV92+dNpu6te+NIETUnlSqyccWQ8oqrT29sNPRF6m53/eG/buNMSh2yMe0cYf+IKO6WeACei78Klbpbk5Fpe+BsUYVyWQhipz8iMJOcupsL+IIYUjKd21hymSTD7TyE835T9c5g5lVIFmPkp5U/X7ZDswgXhqxlVNxIxA0Do0EJeCY3ZcrpJxFMqFUGT6mFx7g+7qlbB/iiDBcu7eP9U1gx04hIWJzfAU5A+VO/5xEp9s7rbr4Jr52GT9CTw3Mc8DEHVNchmGLrxT+cpoxzzkbWVMKVCA3MBwOmRIxwPgEs5kxV7v8btWiB0aGnDA=
    on_success: change
    on_failure: always
